### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by gabrielhdt** [01mf02/kontroli-rs#1]
The following commmands
```
git clone https://github.com/01mf02/kontroli-rs
cd kontroli-rs
cargo run -p kocheck --release examples/pure.ko
```
produce the unexpected following output
```
error[E0658]: use of unstable library feature 'mem_take'
    --> /home/u/.cargo/registry/src/github.com-1ecc6299db9ec823/im-14.3.0/./src/vector/mod.rs:1160:33
     |
1160 |                         middle: std::mem::take(&mut tree.middle),
     |                                 ^^^^^^^^^^^^^^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/61129

error[E0658]: use of unstable library feature 'mem_take'
    --> /home/u/.cargo/registry/src/github.com-1ecc6299db9ec823/im-14.3.0/./src/vector/mod.rs:1181:33
     |
1181 |                         middle: std::mem::take(&mut tree.middle),
     |                                 ^^^^^^^^^^^^^^
     |
     = note: for more information, see https://github.com/rust-lang/rust/issues/61129

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `im`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I use `rustc 1.38.0`

**Comment by 01mf02** [comment]
¡Hola!

I'm sorry to say that you currently need at least Rust 1.40 to compile Kontroli.
I clarified that just now in `README.md`.

**Comment by gabrielhdt** [comment]
Ah, cutting edge rust programming! Beware, the readme reads
> On recent Debian-based systems, this can be installed via

but Debian 10 (the latest stable) uses rust 1.34, but Debian testing (bullseye) uses rust 1.42 <https://packages.debian.org/testing/rust/rustc>.

**Comment by 01mf02** [comment]
:)
Yes, I also checked the Debian packages before putting the note into the README, but I was not sure about what was stable Debian and what was not.
Anyway, I now explicitly wrote "Ubuntu" in the README to clarify this.

**Comment by 01mf02** [comment]
I just checked again whether I could lower the required version number ...
Alas, I use the `alloc` crate stabilised in [Rust 1.36](https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html) quite a lot, so going below version 1.36 will not work.
As version 1.36 does not seem to be any improvement for Debian users, I will keep the requirement for Rust 1.40 for now.

**Comment by gabrielhdt** [comment]
Hello again,
still the same commands
```sh
git clone https://github.com/01mf02/kontroli-rs
cd kontroli-rs
cargo run -p kocheck --release examples/pure.dk
```
fail with  the following message

```
[...]
Compiling spinning_top v0.2.4
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> <home/directory>/.cargo/registry/src/github.com-1ecc6299db9ec823/spinning_top-0.2.4/src/spinlock.rs:57:17
   |
57 |                 hint::spin_loop();
   |                 ^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/55002

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `spinning_top`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
With rust version
```sh
$ rustc --version
rustc 1.41.1
```
(on Debian buster, btw, it has been updated :+1:)
