### ISSUE TITLE
Use of unstable library feature prevents compiling

### ISSUE THREAD

**Issue by gabrielhdt** [01mf02/kontroli-rs#2]
Hello,
the commands
```sh
git clone https://github.com/01mf02/kontroli-rs
cd kontroli-rs
cargo run -p kocheck --release examples/pure.dk
```
fail with  the following message

```
[...]
Compiling spinning_top v0.2.4
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> <home/directory>/.cargo/registry/src/github.com-1ecc6299db9ec823/spinning_top-0.2.4/src/spinlock.rs:57:17
   |
57 |                 hint::spin_loop();
   |                 ^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/55002

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `spinning_top`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
With rust version
```sh
$ rustc --version
rustc 1.41.1
```
(on Debian buster, btw, it has been updated :+1:)

**Comment by 01mf02** [comment]
This error message comes from a dependency of Kontroli.
I am currently rewriting a rather large part of Kontroli and will update the README once this is done, but until then, I can compile Kontroli just fine using Rust 1.51. :)
(I remember having had a problem with updating to Rust 1.53, though, but as I was in the middle of a larger step, I did not research it yet. Just be aware of that if it fails with 1.53.)

**Comment by 01mf02** [comment]
You can install Rust 1.51 with `rustup toolchain install 1.51`.

**Comment by 01mf02** [comment]
The minimal Rust version for Kontroli is now set to 1.56 and checked by the compiler, so error messages such as those encountered by you should not appear anymore.
